[package]
name = "lambda_calculus"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "6"
antlr-rust = { path = "../antlr4rust" }

[[bin]]
name = "repl"
path = "src/repl.rs"
